stages:
  - test
  - deployement

job_test:
  image: php:7.4
  before_script:
    - apt-get update -y
    - composer update
    - composer install

  script:
    - phpunit phpunit_myapp.xml tests

job_deployment:
  script:
    - echo "Déploiement en cours..."
