stages:
  - test
  - deployement

job_test:
  image: php:7.4
  before_script:
    - apt-get update -y
    - apt-get install -y curl
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
    - php composer.phar update
  script:
    - phpunit phpunit_myapp.xml tests

job_deployment:
  script:
    - echo "Déploiement en cours..."
